### ISSUE TITLE
testHistogram fails

### ISSUE THREAD

**Issue by haesleinhuepf** [nicost/cl-kernel-bindings#2]
Hi @nicost ,

I'm trying to make your testHistogram method run with the updated/new kernels in `clij-opencl-kernels`. On my Intel UHD 620 it fails - the minimum intensity determined the opencl-way always is zero. When executing the test with some additional print statements shown here:
https://github.com/haesleinhuepf/cl-kernel-bindings/commit/42a28c5eab20b6cd7b743a4ea7b01def7815840f

It outputs
```
java min: 2684.0
java max: 23129.0
opencl min: 0.0
opencl max: 23129.0
 0:  CPU: 1, GPU: 0
 1:  CPU: 0, GPU: 0
 2:  CPU: 0, GPU: 0
 3:  CPU: 0, GPU: 0
....

Do you have any idea why?

Thanks!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
I also added a minimum (not) working example of the bug:
https://github.com/haesleinhuepf/cl-kernel-bindings/commit/6bb19a8a394386d1030ba9146a8b51a807576017

This test:
```
   @Test
   public void simpleBufferTest() throws CLKernelException {
      short[] floatArray = {
              1, 2,
              3, 4
      };
      ClearCLBuffer buffer = gCLKE.createCLBuffer(new long[]{2,2}, NativeTypeEnum.UnsignedShort);

      buffer.readFrom(ShortBuffer.wrap(floatArray), true);

      float[] minMax = Kernels.minMax(gCLKE, buffer, 2);

      System.out.println("min: " + minMax[0]);
      System.out.println("max: " + minMax[1]);

      assertEquals(1, minMax[0],0);
      assertEquals(4, minMax[1], 0);
   }
```

Should result in min=1 and max=4. But outputs:

```
min: 0.0
max: 4.0

java.lang.AssertionError: 
Expected :1.0
Actual   :0.0
```

Could you please dig into this?

Also, please feel free to push directly to clij-opencl-kernels/master in case that's necessary to fix the bug.

Thanks!

Cheers,
Robert

**Comment by nicost** [comment]
This test works on all systems that I have available (Apple/Intel Iris, NVidia (2 cards), Intel GPU (on Windows), Intel i7 on Windows.  Not sure what I can do about the failure on Intel UHD620..

**Comment by nicost** [comment]
Closing as there is practical way of addressing this issue.  Fixes are welcome.
